naam = input('Wat is je naam?')
adres = input('Wat is je adres?')
postcode = input('Wat is je postcode?')
woonplaats = input('Wat is je woonplaats?')

print(' ----------------------------------------------------')
print(f'|  Naam      : {naam}  ')
print(f'|  Adres     : {adres}')
print(f'|  Postcode  : {postcode}')
print(f'|  Woonplaats: {woonplaats} ')
print(' ----------------------------------------------------')
